### ISSUE TITLE
Throwing error when using keypad.

### ISSUE THREAD

**Issue by blebson** [ethayer/lock-manager#10]
I noticed it while using "Arm Night" on the keypad, returned the following error after the delay:

`c8061ec4-b42d-4a41-9ce3-913bc4d96eb1  9:43:02 PM: debug Keypad manager caught alarm status change: stay
c8061ec4-b42d-4a41-9ce3-913bc4d96eb1  9:43:02 PM: error java.lang.NullPointerException: Cannot get property 'nightRoutine' on null object @ line 123`

Still armed correctly but figured you'd like to know

**Comment by blebson** [comment]
Throws the following error when disarming:

`c8061ec4-b42d-4a41-9ce3-913bc4d96eb1  9:46:27 PM: debug Keypad manager caught alarm status change: off
c8061ec4-b42d-4a41-9ce3-913bc4d96eb1  9:46:27 PM: error java.lang.NullPointerException: Cannot get property 'disarmRoutine' on null object @ line 113`

**Comment by ethayer** [comment]
https://github.com/ethayer/lock-manager/commit/8cf8d4fabe72b9f3c4b8b45e276ecf2d3fbbee51
