### ISSUE TITLE
Lock shown under device, not visible in Lock Manager

### ISSUE THREAD

**Issue by tpitale** [ethayer/lock-manager#16]
After having installed the apps/dth via instructions from: https://dl.dropboxusercontent.com/u/54190708/LockManager/v1.1/guide.pdf

1. Configure 1 lock, and 1 user with code, done and done
2. My Home > Back Door Lock > SmartApps shows Lock: Back Door Lock
3. Return to: Marketplace > My Apps > Lock Manager > **No Locks or Users listed**

This _seems_ like a bug? Not sure.

![img_6293](https://cloud.githubusercontent.com/assets/163/24303137/dfd8035a-1082-11e7-88bc-de7c1973229c.PNG)
![img_6294](https://cloud.githubusercontent.com/assets/163/24303136/dfce353c-1082-11e7-9574-dfa37b4f7433.PNG)

**Comment by tpitale** [comment]
If it matters, I have a kwikset 910 z-wave. Using the zwave-lock-reporting, not the schlage (since it's not a schlage).

**Comment by tpitale** [comment]
Turns out Marketplace > My Apps is not where you want to go to manage. To use after "installation" … go to Automation > SmartApps. That will show installed apps.

**Comment by ethayer** [comment]
Thanks, I'll work this into the user guide to make it more clear.  I don't think you're the only one that gets caught up on that step.
