### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by phoenixfma** [ethayer/lock-manager#18]
Hello,
I'm new to using ST - I have 2 keyless deadbolts (KwikSet & Schlage)

I'm tyring to follow your instructions on installing this lock manager.

On the SmartThings website when I Enable GitHub (I have an account) it either adds my account (phoenixfma) or gives me an error when I attempt to add ethayer/lock-manager.  It says (GitHub repository ethayer/lock-manger not found).  I can find it on GitHub when I search for it, but I can't seem to connect through ST...
It automatically adds my personal GitHub but when I try to add a new repository it won't save/says it can't find it.

**Comment by Cfr200** [comment]
I have the same issue

**Comment by cariacou** [comment]
It seems you have a typo.
Should be " ethayer/lock-man**a**ger" and not " ethayer/lock-manger"

**Comment by phoenixfma** [comment]
Thank you - that worked!
    Actually it's your instructions that are incorrect.  I copied
      directly from your instructions so I wouldn't make an error. 
      Below is a pic showing your installation guide.
    
    
      
      
      Renee Chandler
      Phoenix
            Fitness & Martial Arts
        
          
            
              
                
                  
                     3957 Deep Rock Rd
                     Henrico, VA 23233
                    804.339.1950 (c)
                    www.PhoenixFMA.com
                    https://www.facebook.com/phoenixfma
                    
                  
                
              
            
          
        
      
    
    On 4/3/2017 1:16 PM, cariacou wrote:
    
    
      It seems you have a typo.
        Should be " ethayer/lock-manager" and not "
        ethayer/lock-manger"
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ethayer/lock-manager","title":"ethayer/lock-manager","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ethayer/lock-manager"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cariacou in #18: It seems you have a typo.\r\nShould be \" ethayer/lock-man**a**ger\" and not \" ethayer/lock-manger\"\r\n"}],"action":{"name":"View Issue","url":"https://github.com/ethayer/lock-manager/issues/18#issuecomment-291210497"}}}

**Comment by phoenixfma** [comment]
![2017-04-04_1919](https://cloud.githubusercontent.com/assets/26821123/24683212/c7d8d2e2-196b-11e7-8f07-081edf87ccf6.png)

**Comment by phoenixfma** [comment]
OK - got to Device Handler and added my locks (I have 2 different brands)
But when I go to Device List - nothing shows...
It's been 15 mins - does it take that long to load?

**Comment by ethayer** [comment]
Thanks!  I will fix the typo in the installation guide.  I appreciate it.
