### ISSUE TITLE
No Devices

### ISSUE THREAD

**Issue by phoenixfma** [ethayer/lock-manager#21]
I've gotten the program (?) installed but when I get to the activate custom DTH for your device, I don't have any devices listed.

Am I missing a step?

Thanks

**Comment by CardenInsurance** [comment]
For me, I had to click on My Locations, select the location, and then it asked me to sign in again.  I signed in again.  Then, it acted like I was starting all over, so I had to re-do all the instructions to set up GitHub integration and link to the ethlayer projects again.  But it all worked after that.

**Comment by ethayer** [comment]
You may be on a different shard on the SmartThings server.  Please contact SmartThings customer support about this issue, as it's not an issue specifically caused by the app.
