### ISSUE TITLE
"Scheduling" disables access to "User" profile

### ISSUE THREAD

**Issue by dlgbrown** [ethayer/lock-manager#23]
Hi, E.  Great App.  

I've no issue setting up a "User" profile.

However, if I then access the "User" profile to add a schedule for the "User," after choosing my options and hitting "Done," I receive the following message "You are not authorized to perform the requested operation;" after which time I hit "Done" again and return to the Lock Manager screen, but am no longer able to access the "User" profile, and my only option is to swipe left (iPhone 6) and delete the user profile.  

I'm not a programmer, so assistance in laymen's terms would be appreciated.  

Forgot to mention that my lock is a Schlage Connect.

Thanks in advance.

~L

**Comment by ethayer** [comment]
Duplicate #24

**Comment by dlgbrown** [comment]
Eric - i'm not certain why this is closed, as i'm still experiencing the same problem
please advise if i need to delete and reinstall Lock Manager for it to work correctly
thanx in advance
~L

**Comment by ethayer** [comment]
Did you update your app?

**Comment by dlgbrown** [comment]
do i update the SmartThings App or just the Lock Manager portion of the App?

**Comment by ethayer** [comment]
Go to the IDE and under 'My Apps' click 'Update from repo' and then 'lock-manager'

from there, check any app under 'Obsolete (updated in GitHub)' and then click 'Execute Update'

**Comment by dlgbrown** [comment]
oh, boy - i think i did something wrong
no matter what i try to do in the Lock Manager App, i'm receiving the message "an unexpected error occurred" - including deleting the Lock Manager App
i tried to delete the Lock Manager App in the hub so that i could reinstall it, but am receiving message "SmartApp can't be deleted at this time because it is installed by one or more users"
please help

**Comment by dlgbrown** [comment]
please disregard - figured out how to copy and paste the code into the existing Apps and wah-lah! it works again - thanks for everything, E
