### ISSUE TITLE
Error message " You are not authorized to perform the requested operation"

### ISSUE THREAD

**Issue by amytai168** [ethayer/lock-manager#25]
I add user code on the lock manager with setting the calendar. I set start date/time and end date/time.
After I complete the process, I tried to go inside this user to take a look the setting. I got a error message that "You are not authorized to perform the requested operation".  I can not edit or delete this user code.
What Can I do to reset this issue ?

**Comment by philidem** [comment]
I ran into this issue as well.

This error is logged:

`groovy.lang.MissingMethodException: No signature of method: script149192238287034945879.yyyy-MM-dd() is applicable for argument types: (null) values: [null] @ line 723`

**Comment by ethayer** [comment]
duplicate #24
