### ISSUE TITLE
Installed lock disappears 

### ISSUE THREAD

**Issue by talshum** [ethayer/lock-manager#31]
After installing the lock and setting up a new lock. It disappears and I cannot see available users / edit

**Comment by rhtapp** [comment]
Im having the same issue

**Comment by bhaynes791** [comment]
Just curios, what lock are you using? Mine is a Kwikset 910 zwave.

**Comment by bhaynes791** [comment]
I figured this out. The data is not being lost. You have to navigate to the page that has all your smart apps listed to see the installed lock. If you keep trying to enter where you first installed the app you will just keep installing it new over and over and you will not see lock and code data that you entered. Seems awkward to me but at least now i know how to use the app. This also solved the issue when trying to delete the app. Using Smartthings by the way.

**Comment by ethayer** [comment]
Thanks, @bhaynes791.
