### ISSUE TITLE
Unable to create "New User" with secondary account

### ISSUE THREAD

**Issue by dlgbrown** [ethayer/lock-manager#33]
Hi, E - me, again.  

I'm the primary SmartThings account holder, and I sent my hubby an invite giving him access to the account.  And while he has no problem accessing Lock Manager via SmartThings, and he is able to view the "User(s)" I've set-up, he is unable to set-up "New Users."  When he chooses the option nothing happens.

Is this supposed to happen?

**Comment by ethayer** [comment]
They might have to install the apps on their IDE in order to access them... or go to your IDE and then publish all the child apps so that they're on your platform, that way the other user can access them.

I don't know why SmartThings has this architected this way....
