### ISSUE TITLE
Appears database entries are being cleared from when the app open and closes and reopens

### ISSUE THREAD

**Issue by rhtapp** [ethayer/lock-manager#34]
Flow of events
1. Add a new lock
2. Add users to a lock
3. Code works fine
4. Close the app
5. Reopen the app by navigating through marketplace, my apps, Lock Manager
6. When on this screen the lock doesn't show up, also users don't show up
7. Once I re-add the lock it clears all previous codes.

**Comment by bhaynes791** [comment]
I am having the exact same problem with a Z wave Kwikset lock. Also when i tried to delete the ap to try again it would not delete from my Smartthings account.

**Comment by bhaynes791** [comment]
I forgot to mention that the ap would not allow me to delete it once it was installed. Could not delete from my phone app or my IDE page. Had to call Smartthings twice to delete the ap after i reloaded it a second time.

**Comment by bhaynes791** [comment]
I figured this out. The data is not being lost. You have to navigate to the page that has all your smart apps listed to see the installed lock. If you keep trying to enter where you first installed the app you will just keep installing it new over and over and you will not see lock and code data that you entered. Seems awkward to me but at least now i know how to use the app. This also solved the issue when trying to delete the app.

**Comment by bhaynes791** [comment]
I forgot to mention that i am using Smartthings hub

**Comment by natedizogg** [comment]
I am having the same issue as originally stated by rhtapp. I am unable to find any other place within SmartThings where "all your smart apps are listed" like bhaynes791 mentions. I would appreciate any help/clarification you can offer. Thanks.

**Comment by bhaynes791** [comment]
As i stated, i was seeing the exact same thing as soon as the app closed. When you open your app go to "automation" You will see "Routines" and "Smartapps" at the top of the page. Go to smartapps there and you should see what you have stored. When I first went there i had created several Lockmanagers that were empty but one of them had the data that i had created. If you always enter the smart app from this page you should be able to add locks, change codes,, etc. It is a great app once you learn how. I have been able to automatically lock doors when i leave , assign temporary codes, even make a specific code do things in the house when i punch in that specific code.

**Comment by natedizogg** [comment]
Ah, thanks for the clarification, bhaynes791. That worked. There are too many areas in the SmartThings app with the subsection "SmartApps." I was looking under "MyHome/Things/SmartApps" and "Marketplace/SmartApps". I didn't realize there was also a "SmartApps" section under the Automation tab. Makes sense now. Thanks for your help!

**Comment by bhaynes791** [comment]
Glad i could help. It is usually the other way around for me.
