### ISSUE TITLE
Sorry, unexpected error message- for New Lock, New User & New Keypad

### ISSUE THREAD

**Issue by seaoats** [ethayer/lock-manager#39]
Hello, i hope someone can help. I have installed the Lock-manager on the back end template, so that I can have access to creating pin-codes for people to enter our home using the yale YRL-220. It is linked to the ST hub and can only lock and unlock. I followed the directions to install the Lock manager smart app onto the ST app, but it continues to state "Sorry, but there was an unexpected error." for any entry (New Lock, New User, New Keypad). 
Please advise

**Comment by ethayer** [comment]
It sounds like you didn't add the child apps to your platform, or maybe you were using a different login or shard when you installed the apps on the IDE.

Go back to the IDE and make sure you installed the children apps.  If you did, publish each of the child apps and try again.

**Comment by seaoats** [comment]
The entire child apps were provided in the code? Those were highlighted and
added in. Still it does not work.
There was no shared login for the lock system. And I logged out and back in
to retry.

**Comment by ethayer** [comment]
Contact SmartThings support. https://support.smartthings.com/hc/en-us
