### ISSUE TITLE
Battery Levels Never Update

### ISSUE THREAD

**Issue by tpitale** [ethayer/lock-manager#41]
Not sure if this is an issue with my Kwikset (910, IIRC) deadbolt, the batteries inside, or something to do with the lock-manager.

The initial batteries in the lock drained pretty quickly, so I swapped for some rechargeable AA batteries fully charged. They've been working great in the lock for 4 months now. Still, the battery shows in the developer dashboard as 1, and there appear to be no events related to battery status. Smartthings iOS app shows the battery level as 1% as well.

Have you heard anything about this? Others in the forum have seen battery levels not updating for hours or days, but never 4 months.

Any tips for debugging are much appreciated!

**Comment by ethayer** [comment]
I believe this to be a platform bug, not a bug in this app. (it also effects the default ST DTH)

**Comment by rcl767** [comment]
Hi - same problem with battery status not updating on Yale locks. Changed batteries 2 weeks ago and status never changed from 1%  Any thoughts?

**Comment by LukeRuppSr** [comment]
I have four Kwikset 916 Z-Wave locks. Two of the locks appear to be reporting the battery level correctly. One lock does not report battery level at all. Another reports 1 percent even after installing a new set of batteries ...
