### ISSUE TITLE
User Guide link to dropbox broken

### ISSUE THREAD

**Issue by seanwhite** [ethayer/lock-manager#64]
Didn't see this in the existing issues. As of Sept 3, 2017, the link for the User Guide for installation appears to be broken. At least it didn't work for me.

**Comment by koerbcm** [comment]
👍 Likewise

**Comment by ethayer** [comment]
https://www.dropbox.com/s/pfi9ciqmxbjq9lo/guide.pdf?dl=0

Thanks for letting me know.  Dropbox just changed their Public folder policies.
