### ISSUE TITLE
Schlage button no longer locks door

### ISSUE THREAD

**Issue by trigatch4** [ethayer/lock-manager#65]
After following the guide the Schlage button at the top of the keypad can no longer be used to lock the door. It should lock the door with a single tap but now to lock the door you must re-enter your password.

**Comment by ethayer** [comment]
You must enable 'Lock and Leave' from the lock

Tap on:
'My Home' > {Your Lock}

Then tap on the 'Lock and Leave' tile until it reads 'Enabled'

You can then lock the door with the Schlage logo again.
