### ISSUE TITLE
Yale lock status delay

### ISSUE THREAD

**Issue by MickDawg13** [ethayer/lock-manager#7]
Not sure which Z wave lock your using, but with the Yale YRD220 the lock status is incorrect with this device  handler. 

Another user on Github fixed this issue with the Yale lock.

https://github.com/yracine/customYaleLockWithGoodTimeout/blob/master/customlockdevice.groovy

**Comment by ethayer** [comment]
This device handler is just the default one ST gives.  It will be deleted in the next update to this app which doesn't require it.

Sorry for any frustration.

**Comment by MickDawg13** [comment]
No frustration for me, just testing and making sure you are aware. 

Keep up the great work Erik!
