### ISSUE TITLE
Fix keypad arming delay.

### ISSUE THREAD

**Issue by blebson** [ethayer/lock-manager#8]
Currently the delay only applies to the SHM status change, it should apply to both running the chosen routine and settings the SHM status. As I had posted on the community thread, the flow should be something like: Arm Keypad -> Send "setExitDelay" command to keypad -> Wait for "delay" seconds -> Run desired routine and change SHM status.

**Comment by ethayer** [comment]
https://github.com/ethayer/lock-manager/pull/9
