### ISSUE TITLE
adding multiple instances of smartapp not allowed

### ISSUE THREAD

**Issue by blu3dye** [ethayer/lock-manager#91]
I added the beta 2 smartapp in my hub and was able to link it to my first floor lock. I labeled this instance as 1st floor lock manger.  I tried adding a second instance of the smartapp for my second floor rental which needs different codes than the first floor. When trying to add another instance of the smartapp, it goes directly to the first floor lock manager that I just installed. 

I noticed the single instance was set to true. Was this for a reason?

**Comment by tylerjw** [comment]
You can add both locks to the same app and then set users to be tied to specific locks.  If you have multiple locations (multiple hubs) you will need a separate instance for each location with a lock you want to manage.

**Comment by blu3dye** [comment]
thanks tyler. i'm testing out 2 ways.

1. disabling a user for certain locks in the building (i assume this is what you were referring to)
2. i removed the single instance line of code and created separate managers for each lock.
